"""Add phone to buyers

Revision ID: 72a4749c2c70
Revises: 8051b3a04dd1
Create Date: 2025-07-31 17:07:27.078000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a4749c2c70'
down_revision: Union[str, Sequence[str], None] = '8051b3a04dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyers', sa.Column('phone', sa.String(length=25), nullable=True))
    # op.create_unique_constraint(None, 'buyers', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('buyers_phone_key', 'buyers', type_='unique')
    op.drop_column('buyers', 'phone')
    # ### end Alembic commands ###
