"""initial migration

Revision ID: 79a24984a48e
Revises: 
Create Date: 2025-08-04 10:29:44.963442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '79a24984a48e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('offical_name', sa.String(length=200), nullable=True),
    sa.Column('signature', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('offical_name'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('official_name', sa.String(length=100), nullable=False),
    sa.Column('kyc', sa.String(length=100), nullable=True),
    sa.Column('seller_rating', sa.Float(), nullable=True),
    sa.Column('since_active', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_summary', sa.String(length=255), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('product_details', sqlite.JSON(), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('product_category', sa.String(length=50), nullable=False),
    sa.Column('product_sub_category', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('sizes_available', sqlite.JSON(), nullable=True),
    sa.Column('colors_available', sqlite.JSON(), nullable=True),
    sa.Column('material', sa.String(length=50), nullable=True),
    sa.Column('pattern', sa.String(length=50), nullable=True),
    sa.Column('fit_type', sa.String(length=50), nullable=True),
    sa.Column('occasion', sa.String(length=50), nullable=True),
    sa.Column('fabric_care', sa.String(length=100), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('offers', sqlite.JSON(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('main_image_url', sa.String(length=255), nullable=True),
    sa.Column('additional_image_urls', sqlite.JSON(), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('delivery_charge', sa.Float(), nullable=True),
    sa.Column('cod_available', sa.Boolean(), nullable=True),
    sa.Column('dispatch_time', sa.Integer(), nullable=True),
    sa.Column('max_delivery_days', sa.Integer(), nullable=True),
    sa.Column('returnable', sa.Boolean(), nullable=True),
    sa.Column('return_days', sa.Integer(), nullable=True),
    sa.Column('exchange_available', sa.Boolean(), nullable=True),
    sa.Column('warranty', sa.String(length=100), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=255), nullable=True),
    sa.Column('search_tags', sqlite.JSON(), nullable=True),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('gst_percentage', sa.Float(), nullable=True),
    sa.Column('country_of_origin', sa.String(length=50), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('saved_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('reviews')
    op.drop_table('payment_details')
    op.drop_table('order_items')
    op.drop_table('comments')
    op.drop_table('cart_items')
    op.drop_table('saved_addresses')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('sellers')
    op.drop_table('buyers')
    # ### end Alembic commands ###
