"""initial schema

Revision ID: 8051b3a04dd1
Revises: 
Create Date: 2025-07-31 14:05:24.453398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8051b3a04dd1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyers', sa.Column('email', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'buyers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buyers', type_='unique')
    op.drop_column('buyers', 'email')
    # ### end Alembic commands ###
