"""Update phone column in buyers

Revision ID: b6a82827d756
Revises: e8145a47e27c
Create Date: 2025-07-31 22:19:25.446031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a82827d756'
down_revision: Union[str, Sequence[str], None] = 'e8145a47e27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyers', sa.Column('phone', sa.String(length=25), nullable=True))
    op.add_column('buyers', sa.Column('offical_name', sa.String(length=200), nullable=True))
    op.drop_constraint(op.f('buyers_phone_key'), 'buyers', type_='unique')
    op.create_unique_constraint(None, 'buyers', ['offical_name'])
    op.create_unique_constraint(None, 'buyers', ['phone'])
    op.drop_column('buyers', 'phone1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyers', sa.Column('phone1', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'buyers', type_='unique')
    op.drop_constraint(None, 'buyers', type_='unique')
    op.create_unique_constraint(op.f('buyers_phone_key'), 'buyers', ['phone1'], postgresql_nulls_not_distinct=False)
    op.drop_column('buyers', 'offical_name')
    op.drop_column('buyers', 'phone')
    # ### end Alembic commands ###
