"""Update phone column in buyers

Revision ID: de1593a3f468
Revises: e8d18b8e372e
Create Date: 2025-08-01 11:55:03.114125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1593a3f468'
down_revision: Union[str, Sequence[str], None] = 'e8d18b8e372e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyers', sa.Column('signature', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'buyers', ['signature'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buyers', type_='unique')
    op.drop_column('buyers', 'signature')
    # ### end Alembic commands ###
