"""Update phone column in buyers

Revision ID: e7ae548727d5
Revises: de1593a3f468
Create Date: 2025-08-01 12:53:35.195982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ae548727d5'
down_revision: Union[str, Sequence[str], None] = 'de1593a3f468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buyers', 'signature',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.add_column('comments', sa.Column('review_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'reviews', ['review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'review_id')
    op.alter_column('buyers', 'signature',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
