"""added comment + cart model

Revision ID: e8d18b8e372e
Revises: b6a82827d756
Create Date: 2025-08-01 10:06:49.608687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d18b8e372e'
down_revision: Union[str, Sequence[str], None] = 'b6a82827d756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('buyer_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('content', sa.String(), nullable=False))
    op.add_column('comments', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('comments_review_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'buyers', ['buyer_id'], ['id'])
    op.drop_column('comments', 'review_id')
    op.drop_column('comments', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_review_id_fkey'), 'comments', 'reviews', ['review_id'], ['id'])
    op.drop_column('comments', 'created_at')
    op.drop_column('comments', 'rating')
    op.drop_column('comments', 'content')
    op.drop_column('comments', 'product_id')
    op.drop_column('comments', 'buyer_id')
    op.drop_table('cart_items')
    # ### end Alembic commands ###
