"""added subcategory in product

Revision ID: 0edfd3733a4b
Revises: 86aa354e3e94
Create Date: 2025-08-21 12:47:34.927026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0edfd3733a4b'
down_revision: Union[str, Sequence[str], None] = '86aa354e3e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcategories')
    op.drop_table('sub_categories')
    op.add_column('products', sa.Column('subcategory_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'products', 'subcategory', ['subcategory_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'subcategory_id')
    op.create_table('sub_categories',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='sub_categories_category_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sub_categories_pkey')
    )
    op.create_table('subcategories',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='subcategories_category_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subcategories_pkey')
    )
    # ### end Alembic commands ###
