"""Add category one to one relation to product

Revision ID: 1a301b4d453f
Revises: ebb09f2fdf99
Create Date: 2025-08-20 18:07:36.508815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a301b4d453f'
down_revision: Union[str, Sequence[str], None] = 'ebb09f2fdf99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
