"""Add category model and relation to product

Revision ID: 936cff5892ac
Revises: a2b25e3bc589
Create Date: 2025-08-18 21:28:34.330466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936cff5892ac'
down_revision: Union[str, Sequence[str], None] = 'a2b25e3bc589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
