"""Add category relation to product

Revision ID: d5a5f2e6765c
Revises: 87bc94c35be8
Create Date: 2025-08-20 18:01:20.689768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5a5f2e6765c'
down_revision: Union[str, Sequence[str], None] = '87bc94c35be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seller_email', table_name='seller')
    op.drop_index('ix_seller_username', table_name='seller')
    op.drop_table('seller')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller',
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('official_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('kyc', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('seller_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('since_active', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='seller_pkey'),
    sa.UniqueConstraint('phone', name='seller_phone_key')
    )
    op.create_index('ix_seller_username', 'seller', ['username'], unique=False)
    op.create_index('ix_seller_email', 'seller', ['email'], unique=False)
    # ### end Alembic commands ###
